name = "deva-dispatcher"
main = "index.js"
compatibility_date = "2024-12-26"
account_id = "33c782e95366c69c5d3b4317c14a7441"

# Bind to the "deva test" dispatch namespace
[[dispatch_namespaces]]
binding = "DISPATCHER"
namespace = "deva test"

